openapi: 3.0.0
info:
  title: Ethereum JSON-RPC
  version: 1.0.0

servers:
  - url: https://arbitrum.nownodes.io

security:
  - api-keyAuth: []

paths:
  /:
    post:
      tags:
        - eth_newBlockFilter
      summary: Create a new block filter
      operationId: ethNewBlockFilter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - method
                - params
                - id
              properties:
                jsonrpc:
                  type: string
                  example: "2.0"
                method:
                  type: string
                  example: "eth_newBlockFilter"
                params:
                  type: array
                  description: This method does not require any parameters.
                  items: {}
                  example: []
                id:
                  type: integer
                  example: 1
            examples:
              ExampleRequest:
                value:
                  jsonrpc: "2.0"
                  method: "eth_newBlockFilter"
                  params: []
                  id: 1
      responses:
        "200":
          description: Filter ID created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                    example: "2.0"
                  id:
                    type: integer
                    example: 1
                  result:
                    type: string
                    description: Filter identifier as a hex string.
                    example: "0x16"
              examples:
                ExampleResponse:
                  value:
                    jsonrpc: "2.0"
                    id: 1
                    result: "0x16"

components:
  securitySchemes:
    api-keyAuth:
      type: apiKey
      in: header
      name: api-key
