openapi: 3.0.0
info:
  title: Ethereum JSON-RPC
  version: 1.0.0

servers:
  - url: https://arbitrum.nownodes.io

security:
  - api-keyAuth: []

paths:
  /:
    post:
      tags:
        - eth_getBlockTransactionCountByNumber
      summary: Get Transaction Count by Block Number
      operationId: ethGetBlockTransactionCountByNumber
      description: |
        Returns the number of transactions contained in the block with the given block number.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - method
                - params
                - id
              properties:
                jsonrpc:
                  type: string
                  example: "2.0"
                  description: JSON-RPC version
                method:
                  type: string
                  example: "eth_getBlockTransactionCountByNumber"
                  description: JSON-RPC method name
                params:
                  type: array
                  minItems: 1
                  maxItems: 1
                  description: |
                    Array containing a single parameter:
                      - Block number as a hex string (e.g. "0x10d4f" for block 69007) or
                      - predefined block tags such as "latest", "earliest", or "pending"
                  items:
                    type: string
                    example: "0x10d4f"
                id:
                  type: integer
                  example: 1
                  description: Request ID
      responses:
        '200':
          description: Number of transactions in the block
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                    example: "2.0"
                    description: JSON-RPC version
                  id:
                    type: integer
                    example: 1
                    description: Same ID as in the request
                  result:
                    type: string
                    description: Number of transactions in the block, returned as a hex string
                    example: "0x8" # 8 transactions

components:
  securitySchemes:
    api-keyAuth:
      type: apiKey
      in: header
      name: api-key
