openapi: 3.0.0
info:
  title: Ethereum JSON-RPC
  version: 1.0.0

servers:
  - url: https://arbitrum.nownodes.io

security:
  - api-keyAuth: []

paths:
  /:
    post:
      tags:
        - eth_sendTransaction
      summary: Send a transaction using node-managed account
      operationId: ethSendTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - method
                - params
                - id
              properties:
                jsonrpc:
                  type: string
                  example: "2.0"
                method:
                  type: string
                  example: "eth_sendTransaction"
                params:
                  type: array
                  description: Transaction object
                  minItems: 1
                  maxItems: 1
                  items:
                    type: object
                    properties:
                      from:
                        type: string
                        description: Address the transaction is sent from
                        example: "0x6A0bF1017C6e6Dd9D2BA447E2AAd951F13F7F7C3"
                      to:
                        type: string
                        description: Address the transaction is directed to
                        example: "0x742d35Cc6634C0532925a3b844Bc454e4438f44e"
                      gas:
                        type: string
                        description: Gas provided for the transaction (hex)
                        example: "0x5208"
                      gasPrice:
                        type: string
                        description: Gas price in wei (hex)
                        example: "0x3b9aca00"
                      value:
                        type: string
                        description: Value sent with the transaction in wei (hex)
                        example: "0x16345785d8a0000"
                      data:
                        type: string
                        description: (Optional) Data for contract interaction
                        example: "0x"
                id:
                  type: integer
                  example: 1
            examples:
              ExampleRequest:
                value:
                  jsonrpc: "2.0"
                  method: "eth_sendTransaction"
                  params:
                    - from: "0x6A0bF1017C6e6Dd9D2BA447E2AAd951F13F7F7C3"
                      to: "0x742d35Cc6634C0532925a3b844Bc454e4438f44e"
                      gas: "0x5208"
                      gasPrice: "0x3b9aca00"
                      value: "0x16345785d8a0000"
                      data: "0x"
                  id: 1
      responses:
        "200":
          description: Transaction successfully sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                    example: "2.0"
                  id:
                    type: integer
                    example: 1
                  result:
                    type: string
                    description: Transaction hash
                    example: "0x5f5c67a3120bb6e038f8460cb2e8393dcd1704b2e1ef7689e3ec6b867a2bcae4"
              examples:
                ExampleResponse:
                  value:
                    jsonrpc: "2.0"
                    id: 1
                    result: "0x5f5c67a3120bb6e038f8460cb2e8393dcd1704b2e1ef7689e3ec6b867a2bcae4"

components:
  securitySchemes:
    api-keyAuth:
      type: apiKey
      in: header
      name: api-key
