openapi: 3.0.0
info:
  title: Ethereum JSON-RPC
  version: 1.0.0

servers:
  - url: https://arbitrum.nownodes.io

security:
  - api-keyAuth: []

paths:
  /:
    post:
      tags:
        - eth_hashrate
      summary: eth_hashrate
      description: >
        Returns the current mining hashrate reported by the client.
      operationId: eth_hashrate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - method
                - params
                - id
              properties:
                jsonrpc:
                  type: string
                  example: "2.0"
                method:
                  type: string
                  enum: [eth_hashrate]
                  example: "eth_hashrate"
                params:
                  type: array
                  description: This method takes no parameters.
                  maxItems: 0
                  example: []
                id:
                  type: integer
                  example: 1
      responses:
        '200':
          description: JSON-RPC response with the current mining hashrate
          content:
            application/json:
              schema:
                type: object
                required: [jsonrpc, id, result]
                properties:
                  jsonrpc:
                    type: string
                    example: "2.0"
                  id:
                    type: integer
                    example: 1
                  result:
                    type: string
                    description: >
                      The current mining hashrate in hashes per second, as a hexadecimal string.
                    example: "0x3b9aca00"

components:
  securitySchemes:
    api-keyAuth:
      type: apiKey
      in: header
      name: api-key
