openapi: 3.0.0
info:
  title: Ethereum JSON-RPC
  version: 1.0.0

servers:
  - url: https://arbitrum.nownodes.io

security:
  - api-keyAuth: []

paths:
  /:
    post:
      tags:
        - eth_getBlockReceipts
      summary: Get All Transaction Receipts for a Block
      operationId: ethGetBlockReceipts
      description: |
        Returns an array of transaction receipts for every transaction in the block specified by block number or block hash.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - method
                - params
                - id
              properties:
                jsonrpc:
                  type: string
                  example: "2.0"
                  description: JSON-RPC version
                method:
                  type: string
                  example: "eth_getBlockReceipts"
                  description: JSON-RPC method name
                params:
                  type: array
                  minItems: 1
                  maxItems: 1
                  description: |
                    One parameter:
                      - Block identifier, which can be either:
                        - block number as hex string (e.g. "0x10d4f")
                        - or block hash as hex string (0x-prefixed)
                  items:
                    type: string
                    example: "0x10d4f"
                id:
                  type: integer
                  example: 1
                  description: Request identifier
      responses:
        '200':
          description: Array of transaction receipts in the block
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                    example: "2.0"
                    description: JSON-RPC version
                  id:
                    type: integer
                    example: 1
                    description: Request ID, same as in the request
                  result:
                    type: array
                    description: Array of transaction receipts objects
                    items:
                      type: object
                      description: A transaction receipt object
                      properties:
                        transactionHash:
                          type: string
                          description: Hash of the transaction
                          example: "0x5f4e3b4f5c4c4a6a93c2a3c9d1f47ee7e54b1f4e8a8e0cfd3aabb8a7a8295f7a"
                        transactionIndex:
                          type: string
                          description: Hexadecimal index position of the transaction in the block
                          example: "0x1"
                        blockHash:
                          type: string
                          description: Hash of the block containing the transaction
                          example: "0xabc123def456..."
                        blockNumber:
                          type: string
                          description: Hexadecimal block number containing the transaction
                          example: "0x10d4f"
                        from:
                          type: string
                          description: Address of the sender
                          example: "0x1234567890abcdef1234567890abcdef12345678"
                        to:
                          type: string
                          nullable: true
                          description: Address of the receiver; null if contract creation
                          example: "0xabcdefabcdefabcdefabcdefabcdefabcdef"
                        cumulativeGasUsed:
                          type: string
                          description: Total gas used when this transaction was executed in the block (hex)
                          example: "0x5208"
                        gasUsed:
                          type: string
                          description: Gas used by this specific transaction alone (hex)
                          example: "0x5208"
                        contractAddress:
                          type: string
                          nullable: true
                          description: Contract address created, if the transaction was a contract creation
                          example: "0xcontractaddresshere"
                        logs:
                          type: array
                          description: Array of log objects generated by this transaction
                          items:
                            type: object
                            properties:
                              removed:
                                type: boolean
                                description: True if the log was removed, e.g. due to chain reorganization
                                example: false
                              logIndex:
                                type: string
                                description: Hexadecimal index position of the log in the block
                                example: "0x0"
                              transactionIndex:
                                type: string
                                description: Hexadecimal index of the transaction in the block
                                example: "0x1"
                              transactionHash:
                                type: string
                                description: Hash of the transaction this log belongs to
                                example: "0x5f4e3b4f5c4c4a6a93c2a3c9d1f47ee7e54b1f4e8a8e0cfd3aabb8a7a8295f7a"
                              blockHash:
                                type: string
                                description: Hash of the block containing the log
                                example: "0xabc123def456..."
                              blockNumber:
                                type: string
                                description: Hexadecimal block number containing the log
                                example: "0x10d4f"
                              address:
                                type: string
                                description: Address from which this log originated
                                example: "0xcontractaddresshere"
                              data:
                                type: string
                                description: Contains the non-indexed arguments of the log
                                example: "0x0000000000000000000000000000000000000000000000000000000000000000"
                              topics:
                                type: array
                                description: Array of indexed event topics
                                items:
                                  type: string
                                example:
                                  - "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
                        status:
                          type: string
                          description: 'Transaction status: "0x1" = success, "0x0" = failure (optional, if supported)'
                          example: "0x1"
                        root:
                          type: string
                          description: Pre-Byzantium transactions root (optional)
                          example: "0x..."

components:
  securitySchemes:
    api-keyAuth:
      type: apiKey
      in: header
      name: api-key
