openapi: 3.0.0
info:
  title: Ethereum JSON-RPC
  version: 1.0.0

servers:
  - url: https://arbitrum.nownodes.io

security:
  - api-keyAuth: []

paths:
  /:
    post:
      tags:
        - eth_getUncleCountByBlockHash
      summary: Get the number of uncle blocks by block hash
      operationId: ethGetUncleCountByBlockHash
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - method
                - params
                - id
              properties:
                jsonrpc:
                  type: string
                  example: "2.0"
                method:
                  type: string
                  example: "eth_getUncleCountByBlockHash"
                params:
                  type: array
                  minItems: 1
                  maxItems: 1
                  description: An array containing the block hash.
                  items:
                    type: string
                    description: Hash of the block (32-byte hex string prefixed with `0x`).
                  example:
                    - "0x9b559a937406429b662b9bd5b2be3c7a2ed36b5a0dbcf0d07a987f695705daec"
                id:
                  type: integer
                  example: 1
            examples:
              ExampleRequest:
                value:
                  jsonrpc: "2.0"
                  method: "eth_getUncleCountByBlockHash"
                  params:
                    - "0x9b559a937406429b662b9bd5b2be3c7a2ed36b5a0dbcf0d07a987f695705daec"
                  id: 1
      responses:
        "200":
          description: Number of uncles in the block
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                    example: "2.0"
                  id:
                    type: integer
                    example: 1
                  result:
                    type: string
                    description: |
                      The number of uncle blocks as a hex string (e.g., "0x2" for 2 uncles).
              examples:
                ExampleResponse:
                  value:
                    jsonrpc: "2.0"
                    id: 1
                    result: "0x1"

components:
  securitySchemes:
    api-keyAuth:
      type: apiKey
      in: header
      name: api-key
