openapi: 3.0.0
info:
  title: Ethereum JSON-RPC
  version: 1.0.0

servers:
  - url: https://arbitrum.nownodes.io

security:
  - api-keyAuth: []

paths:
  /:
    post:
      tags:
        - eth_signTransaction
      summary: eth_signTransaction
      description: >
        Signs a transaction locally with the private key of the specified account.
      operationId: eth_signTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - method
                - params
                - id
              properties:
                jsonrpc:
                  type: string
                  example: "2.0"
                method:
                  type: string
                  enum: [eth_signTransaction]
                  example: "eth_signTransaction"
                params:
                  type: array
                  description: >
                    Array with a single object representing the transaction to sign.
                  items:
                    type: object
                    required:
                      - from
                    properties:
                      from:
                        type: string
                        description: >
                          The address of the account that will sign the transaction.
                        example: "0x407d73d8a49eeb85d32cf465507dd71d507100c1"
                      to:
                        type: string
                        description: >
                          The destination address of the transaction.
                        example: "0x85a3d76e3a6a4b16b5b442c1b11a03bdcc0a9f30"
                      gas:
                        type: string
                        description: >
                          Gas limit for the transaction, as a hex string.
                        example: "0x5208"
                      gasPrice:
                        type: string
                        description: >
                          Gas price in wei, as a hex string.
                        example: "0x4a817c800"
                      value:
                        type: string
                        description: >
                          Amount of wei to send, as a hex string.
                        example: "0xde0b6b3a7640000"
                      data:
                        type: string
                        description: >
                          Data payload of the transaction, hex encoded.
                        example: "0x"
                      nonce:
                        type: string
                        description: >
                          Nonce of the transaction, as a hex string.
                        example: "0x1"
                      chainId:
                        type: integer
                        description: >
                          The chain ID to protect against replay attacks.
                        example: 1
                  minItems: 1
                  maxItems: 1
                id:
                  type: integer
                  example: 1
      responses:
        '200':
          description: JSON-RPC response with the signed transaction data
          content:
            application/json:
              schema:
                type: object
                required: [jsonrpc, id, result]
                properties:
                  jsonrpc:
                    type: string
                    example: "2.0"
                  id:
                    type: integer
                    example: 1
                  result:
                    type: string
                    description: >
                      The signed transaction serialized and encoded as a hex string, ready to be sent via `eth_sendRawTransaction`.
                    example: "0xf86c808504a817c80082520894b60e8dd61c5d32be8058bb8eb970870f072331550880de0b6b3a76400008025a08b5a9e4f3e93096d046a9e4d4f28e0e2aab034c8998a2a4015304e80a40338c5a047d092f3246c4e11d995cbca7ed8a47aaf3dfeff8b6af33d57f4caba1c88b52c7"

components:
  securitySchemes:
    api-keyAuth:
      type: apiKey
      in: header
      name: api-key
