openapi: 3.0.0
info:
  title: Ethereum JSON-RPC
  version: 1.0.0

servers:
  - url: https://arbitrum.nownodes.io

security:
  - api-keyAuth: []

paths:
  /:
    post:
      tags:
        - eth_call
      summary: Ethereum method - eth_call
      description: |
        Executes a call to a contract or address and returns the result without broadcasting a transaction.
      operationId: ethCall
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [jsonrpc, method, params, id]
              properties:
                jsonrpc:
                  type: string
                  example: "2.0"
                method:
                  type: string
                  example: "eth_call"
                params:
                  type: array
                  minItems: 1
                  maxItems: 2
                  description: |
                    The first object specifies the call transaction object.
                    The second (optional) parameter specifies the block context.
                  items:
                    oneOf:
                      - type: object
                        title: Call Object
                        required: [to]
                        properties:
                          from:
                            type: string
                            description: Address the call is sent from (optional)
                            example: "0x742d35Cc6634C0532925a3b844Bc454e4438f44e"
                          to:
                            type: string
                            description: Target address for the call (required)
                            example: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
                          gas:
                            type: string
                            description: Gas provided for the call, as hex
                            example: "0x76c0"
                          gasPrice:
                            type: string
                            description: Gas price in wei, as hex
                            example: "0x9184e72a000"
                          value:
                            type: string
                            description: Amount of ETH sent, as hex (optional)
                            example: "0x0"
                          data:
                            type: string
                            description: Compiled contract method call data
                            example: "0x70a08231000000000000000000000000a0df350d2637096571f7a701cbc1c5fd..."                          
                      - type: string
                        title: Block Tag
                        description: |
                          (Optional) Integer block number, or the string "latest", "earliest", or "pending".
                        example: "latest"
                id:
                  type: integer
                  example: 1
      responses:
        '200':
          description: Result of the call
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                    example: "2.0"
                  id:
                    type: integer
                    example: 1
                  result:
                    type: string
                    description: |
                      Return value of the executed contract call, encoded as hex.
                      This is the raw output — typically ABI-decoded on the client.
                    example: "0x00000000000000000000000000000000000000000000000000000000000003e8"

components:
  securitySchemes:
    api-keyAuth:
      type: apiKey
      in: header
      name: api-key
