openapi: 3.0.0
info:
  title: Ethereum JSON-RPC
  version: 1.0.0

servers:
  - url: https://arbitrum.nownodes.io

security:
  - api-keyAuth: []

paths:
  /:
    post:
      tags:
        - eth_getUncleCountByBlockNumber
      summary: Get the number of uncle blocks by block number
      operationId: ethGetUncleCountByBlockNumber
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - method
                - params
                - id
              properties:
                jsonrpc:
                  type: string
                  example: "2.0"
                method:
                  type: string
                  example: "eth_getUncleCountByBlockNumber"
                params:
                  type: array
                  minItems: 1
                  maxItems: 1
                  description: An array containing the block number as a hex string.
                  items:
                    type: string
                    description: |
                      The block number to query, expressed as a hex string prefixed with `0x`.
                      Special strings "latest", "earliest", or "pending" are also accepted.
                  example:
                    - "0x10d4f"  # decimal 69007
                id:
                  type: integer
                  example: 1
            examples:
              ExampleRequest:
                value:
                  jsonrpc: "2.0"
                  method: "eth_getUncleCountByBlockNumber"
                  params:
                    - "0x10d4f"
                  id: 1
      responses:
        "200":
          description: Number of uncle blocks in the block
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                    example: "2.0"
                  id:
                    type: integer
                    example: 1
                  result:
                    type: string
                    description: |
                      The number of uncle blocks as a hex string (e.g., "0x0" for zero uncles).
              examples:
                ExampleResponse:
                  value:
                    jsonrpc: "2.0"
                    id: 1
                    result: "0x2"

components:
  securitySchemes:
    api-keyAuth:
      type: apiKey
      in: header
      name: api-key
