openapi: 3.0.0
info:
  title: Ethereum JSON-RPC
  version: 1.0.0

servers:
  - url: https://arbitrum.nownodes.io

security:
  - api-keyAuth: []

paths:
  /:
    post:
      tags:
        - eth_getBlockTransactionCountByHash
      summary: Get Transaction Count by Block Hash
      operationId: ethGetBlockTransactionCountByHash
      description: |
        Returns the number of transactions contained in the block with the given hash.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - method
                - params
                - id
              properties:
                jsonrpc:
                  type: string
                  example: "2.0"
                  description: JSON-RPC version
                method:
                  type: string
                  example: "eth_getBlockTransactionCountByHash"
                  description: JSON-RPC method name
                params:
                  type: array
                  minItems: 1
                  maxItems: 1
                  description: |
                    Array containing a single parameter:
                      - Block hash as a hex string (32 bytes with 0x prefix)
                  items:
                    type: string
                    example: "0x9b559a3d7ee67a0a8bb96ec93c93a0db3f9c66a355a3eb9f3f519c0f26a27c79"
                id:
                  type: integer
                  example: 1
                  description: Request ID
      responses:
        '200':
          description: Number of transactions in the block
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                    example: "2.0"
                    description: JSON-RPC version
                  id:
                    type: integer
                    example: 1
                    description: Same ID as in request
                  result:
                    type: string
                    description: Number of transactions in the block, returned as a hex string
                    example: "0x8" # 8 transactions

components:
  securitySchemes:
    api-keyAuth:
      type: apiKey
      in: header
      name: api-key
