openapi: 3.0.0
info:
  title: Ethereum JSON-RPC
  version: 1.0.0

servers:
  - url: https://arbitrum.nownodes.io

security:
  - api-keyAuth: []

paths:
  /:
    post:
      tags:
        - eth_newFilter
      summary: Create a new log filter
      operationId: ethNewFilter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - method
                - params
                - id
              properties:
                jsonrpc:
                  type: string
                  example: "2.0"
                method:
                  type: string
                  example: "eth_newFilter"
                params:
                  type: array
                  description: Array with one object describing the filter options.
                  items:
                    type: object
                    properties:
                      fromBlock:
                        type: string
                        description: Starting block number or tag (`"latest"`, `"earliest"`, `"pending"`).
                        example: "latest"
                      toBlock:
                        type: string
                        description: Ending block number or tag.
                        example: "latest"
                      address:
                        oneOf:
                          - type: string
                            description: Single address to filter by.
                            example: "0x1234567890abcdef1234567890abcdef12345678"
                          - type: array
                            description: Multiple addresses to filter by.
                            items:
                              type: string
                        nullable: true
                      topics:
                        type: array
                        description: Array of topic filters. Topics are 32-byte hashes identifying events.
                        items:
                          oneOf:
                            - type: string
                            - type: array
                              items:
                                type: string
                        nullable: true
                  example:
                    - fromBlock: "latest"
                      toBlock: "latest"
                      address: "0x1234567890abcdef1234567890abcdef12345678"
                      topics:
                        - "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
                id:
                  type: integer
                  example: 1
            examples:
              ExampleRequest:
                value:
                  jsonrpc: "2.0"
                  method: "eth_newFilter"
                  params:
                    - fromBlock: "latest"
                      toBlock: "latest"
                      address: "0x1234567890abcdef1234567890abcdef12345678"
                      topics:
                        - "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
                  id: 1
      responses:
        "200":
          description: Filter ID created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                    example: "2.0"
                  id:
                    type: integer
                    example: 1
                  result:
                    type: string
                    description: Filter identifier as a hex string.
                    example: "0x16"
              examples:
                ExampleResponse:
                  value:
                    jsonrpc: "2.0"
                    id: 1
                    result: "0x16"

components:
  securitySchemes:
    api-keyAuth:
      type: apiKey
      in: header
      name: api-key
