openapi: 3.0.0
info:
  title: Ethereum JSON-RPC
  version: 1.0.0

servers:
  - url: https://arbitrum.nownodes.io

security:
  - api-keyAuth: []

paths:
  /:
    post:
      tags:
        - net_listening
      summary: net_listening
      description: >
        Checks if the client is listening for network connections.
      operationId: net_listening
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - method
                - params
                - id
              properties:
                jsonrpc:
                  type: string
                  example: "2.0"
                method:
                  type: string
                  enum: [net_listening]
                  example: "net_listening"
                params:
                  type: array
                  description: This method takes no parameters.
                  maxItems: 0
                  example: []
                id:
                  type: integer
                  example: 1
      responses:
        '200':
          description: JSON-RPC response with listening status
          content:
            application/json:
              schema:
                type: object
                required: [jsonrpc, id, result]
                properties:
                  jsonrpc:
                    type: string
                    example: "2.0"
                  id:
                    type: integer
                    example: 1
                  result:
                    type: boolean
                    description: >
                      `true` if the client is listening for network connections, otherwise `false`.
                    example: true

components:
  securitySchemes:
    api-keyAuth:
      type: apiKey
      in: header
      name: api-key
