openapi: 3.0.0
info:
  title: Ethereum JSON-RPC
  version: 1.0.0

servers:
  - url: https://arbitrum.nownodes.io

security:
  - api-keyAuth: []

paths:
  /:
    post:
      tags:
        - net_version
      summary: net_version
      description: >
        Returns the current network ID of the Ethereum client.
      operationId: net_version
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - method
                - params
                - id
              properties:
                jsonrpc:
                  type: string
                  example: "2.0"
                method:
                  type: string
                  enum: [net_version]
                  example: "net_version"
                params:
                  type: array
                  description: This method takes no parameters.
                  maxItems: 0
                  example: []
                id:
                  type: integer
                  example: 1
      responses:
        '200':
          description: JSON-RPC response with the current network ID
          content:
            application/json:
              schema:
                type: object
                required: [jsonrpc, id, result]
                properties:
                  jsonrpc:
                    type: string
                    example: "2.0"
                  id:
                    type: integer
                    example: 1
                  result:
                    type: string
                    description: >
                      The network ID as a decimal string.
                    example: "1"

components:
  securitySchemes:
    api-keyAuth:
      type: apiKey
      in: header
      name: api-key
