openapi: 3.0.0
info:
  title: Ethereum JSON-RPC
  version: 1.0.0

servers:
  - url: https://arbitrum.nownodes.io

security:
  - api-keyAuth: []

paths:
  /:
    post:
      tags:
        - net_peerCount
      summary: net_peerCount
      description: >
        Returns the number of peers currently connected to the client.
      operationId: net_peerCount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - method
                - params
                - id
              properties:
                jsonrpc:
                  type: string
                  example: "2.0"
                method:
                  type: string
                  enum: [net_peerCount]
                  example: "net_peerCount"
                params:
                  type: array
                  description: This method takes no parameters.
                  maxItems: 0
                  example: []
                id:
                  type: integer
                  example: 1
      responses:
        '200':
          description: JSON-RPC response with the number of connected peers
          content:
            application/json:
              schema:
                type: object
                required: [jsonrpc, id, result]
                properties:
                  jsonrpc:
                    type: string
                    example: "2.0"
                  id:
                    type: integer
                    example: 1
                  result:
                    type: string
                    description: >
                      The number of peers currently connected, as a hexadecimal string.
                    example: "0x8"

components:
  securitySchemes:
    api-keyAuth:
      type: apiKey
      in: header
      name: api-key
